services:
  main_container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    image: hrisim:latest
    container_name: HRISim-darko
    user: ${UID:-1000}:${GID:-1000}

    stdin_open: true
    tty: true
    privileged: true

    gpus: all
    runtime: nvidia

    volumes:
      - ./HRISim_docker/src/HRISim:/home/hrisim/ros_ws/src/HRISim
      - ./HRISim_docker/src/pedsim_ros:/home/hrisim/ros_ws/src/pedsim_ros
      - ./HRISim_docker/src/darko_orchestrator:/home/hrisim/ros_ws/src/darko_orchestrator
      - ./shared:/home/hrisim/shared
      - ./HRISim_docker/src/HRISim/hrisim_gazebo/tiago_maps/:/home/hrisim/.pal/tiago_maps/configurations/
      - ./HRISim_docker/src/HRISim/hrisim_gazebo/models:/home/hrisim/.gazebo/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - LIBGL_ALWAYS_INDIRECT=0

    network_mode: "host"